### ISSUE TITLE
GooglePlay problem

### ISSUE THREAD

**Issue by djsiropchik** [X-s/patchrom_miui_oneplus_bacon#10]
Can not install applications from GP. I get an error: "out of memory"
Pls fix it, bro!

**Comment by X-s** [comment]
i'm not have any good way to fix it...sorry..(:

**Comment by dadaz** [comment]
Hi,


I've found on oneplus forum a zip with Downloadprovider.apk and Downloadproviderui.apk which fix the low space issue. I can send it to you so you can compare what's the difference with yours and fix them ?

**Comment by dado82rm** [comment]
maybe dadaz is right 
can you have a look to this?
https://github.com/CyanogenMod/android_packages_providers_DownloadProvider/commit/97086b259248d3d46a0d558aff8a32d1c6987777

**Comment by dado82rm** [comment]
X_s check vere and update pleasehttp://forum.xda-developers.com/showpost.php?p=60879880&postcount=593

**Comment by dado82rm** [comment]
just for your information the ota update 5.5.23 didn't work for me it fail saing cant verify downloadprovider.apk (the file that i flashed one post up) so i had to install the full rom 5.5.23 again ad reinstall the downloadprovider.apk.... will i have the same problem with every weekly ota?

**Comment by X-s** [comment]
if you replace downloadprovider.apk, you can't ota..
i don't use your downloadxxxx.apk, i think that is not a good way to fix them..sorry..you can backup apk and ota,them replace your downloadprovider.apk to use google play..sorry

**Comment by dadaz** [comment]
Why do you think it's not a good way to fix the storage bug as it works ? 
Can you explain ?
thanks

**Comment by X-s** [comment]
Xiaomi market have some bugs....in china,people use xiaomi market..

**Comment by djsiropchik** [comment]
Xiaomi fix it?)

**Comment by dadaz** [comment]
5.6.11 doesn't have the error anymore, but playstore downloads never start.

**Comment by X-s** [comment]
not fix...

**Comment by dadaz** [comment]
Yes see that other phones have same behavior with last version.

**Comment by dadaz** [comment]
I've looked a bit at this on 5.6.12.

In fact playstore or play services can download but they never know they download.

If you look at the data usage stats (data or wlan as you use), you will see that play store or play services download a huge amount of data.

You can see this by trying to install an app from playstore, let it try to download and look at the data usage stats in security app.
You will see that play store download some data.

The problem is that as they never know they download, they try to download continuously and use a huge amount of data.

Can you report that to Xiaomi... Don't know how to do that for patchrom. I've already say that on en.miui.com forum, but I think it could be better to report that on chineese forum, but I don't speak chineese.

Thanks for your work.

**Comment by dadaz** [comment]
Hi, I Flashed wuxianlin colorOS MIUI port to compare with yours differences as ColorOS One have Play store working.

I see that in stockage, your version show 351GB of images !!!! ColorsOS Port show the right size.

Here are 2 screenshots. Maybe it's not a download problem, but a stockage problem on your port.
First is from wuxianlin (5.6.21) and second from yours (5.6.19).

![wuxianlin coloros](https://cloud.githubusercontent.com/assets/5988669/8308081/fe2e0970-19c2-11e5-9f70-ef27f01599b9.png)
![x_s cm11](https://cloud.githubusercontent.com/assets/5988669/8308080/fe251edc-19c2-11e5-9c3d-535977382f79.png)

Thanks

**Comment by Alucard666666** [comment]
Hi, is there any chance to fix this bug in future builds?

**Comment by X-s** [comment]
there is no.....i no ways to  fix..

**Comment by shijopj2015** [comment]
Hello Dev X-s..
Thank you for providing us the best ROM miui 6 for oneplus one
We many from international users of the same and unfortunately the google play services issue is persisting. Please help us to solve this issue. We will be always thankful to you.

thanks

**Comment by X-s** [comment]
google play has fix..:)

**Comment by dadaz** [comment]
Yes I have seen it on activity status.

It's a great news. I can switch back to your port as it's the one I prefer.

Thanks.

**Comment by ntilagoa** [comment]
X-s
You are the MAN. 
Thank you very much for your hard work. 
We all love your port of MIUI 6 for our beloved ONE+

**Comment by Scarynix** [comment]
Hello, has you it a link for the fix of the play store ?

**Comment by dadaz** [comment]
It should be in tomorrow release.

**Comment by Scarynix** [comment]
thanks for the answer

**Comment by X-s** [comment]
the miui rom version 5.7.24 not fullota . i will make it afternoon...please waiting :)

**Comment by X-s** [comment]
http://miuirom.xiaomi.com/rom/u27615941/5.7.24/miui_bacon_xs_5.7.24_bce6ce8132_4.4.zip
:)
