### ISSUE TITLE
Screenshot problem

### ISSUE THREAD

**Issue by djsiropchik** [X-s/patchrom_miui_oneplus_bacon#11]
I can not make screenshot. The message "failed to take a picture, the device is busy. try again later"

**Comment by X-s** [comment]
you touch power + volume down? or you can touch systemui power with screen ?

**Comment by djsiropchik** [comment]
i use icon in the panel switch

**Comment by X-s** [comment]
so? can work?

**Comment by dado82rm** [comment]
i can confirm that it work it goes into gallery / local / screenshot  menu

**Comment by X-s** [comment]
can't screenshot?

**Comment by djsiropchik** [comment]
not work in notification tiles. Combination is not iunteresting for me.
