### ISSUE TITLE
MIUI Camera HDR

### ISSUE THREAD

**Issue by dadaz** [X-s/patchrom_miui_oneplus_bacon#12]
Hi,

MIUI Camera is great, but when I use HDR mode, it takes and saves 3 pictures instead of 1.

Thanks for what you can do.

**Comment by X-s** [comment]
in fact, MIUI Camera HDR has some bugs..it can't work.

**Comment by dadaz** [comment]
OK I'll won't use it so.

CameraNext Moded is fine

**Comment by X-s** [comment]
:)
