### ISSUE TITLE
Request for build.prop

### ISSUE THREAD

**Issue by dadaz** [X-s/patchrom_miui_oneplus_bacon#15]
Hi this is not an issue, but I can't open a request.

Could you add these 3 lines in build.prop, it's for fix low mic volume when handsfree calls.

persist.audio.fluence.voicecall=true
persist.audio.fluence.voicerec=false
persist.audio.fluence.speaker=false

Thanks if you can.

**Comment by X-s** [comment]
Are these things really useful?

**Comment by dadaz** [comment]
I can say yes without these lines, peoples don't hear me well and they hear me very well with these three lines.

I can had these lines manually, but as it modifies build.prop, it breaks OTA.

Thanks

**Comment by X-s** [comment]
OK. i will add these to next version

**Comment by dadaz** [comment]
Thank you
