### ISSUE TITLE
Google Play services battery drain

### ISSUE THREAD

**Issue by dadaz** [X-s/patchrom_miui_oneplus_bacon#18]
Hi, thanks again for fixing google play bug.

But there is a known issue with play services that drain battery. There is an easy fix that doesn't pose problem with anything else. You can find it on XDA, here is what you can do, thanks if you can :

Instructions for Modifying Framework

Decompile framework-res.apk and modify values/array.xml, in "config_disabledComponents"

Before - If you don't see this code, then your ROM is not the cause of this wakelock

 <string-array name="config_disabledComponents">
        <item>com.google.android.gsf/com.google.android.gsf.update.SystemUpdateActivity</item>
        <item>com.google.android.gsf/com.google.android.gsf.update.SystemUpdateService</item>
        <item>com.google.android.gsf/com.google.android.gsf.update.SystemUpdateService$Receiver</item>
        <item>com.google.android.gms/com.google.android.gms.update.SystemUpdateActivity</item>
        <item>com.google.android.gms/com.google.android.gms.update.SystemUpdateService</item>
        <item>com.google.android.gms/com.google.android.gms.update.SystemUpdateService$Receiver</item>
        <item>com.google.android.gms/com.google.android.gms.update.SystemUpdateService$ActiveReceiver</item>
    </string-array>

After

<string-array name="config_disabledComponents">
        <item>com.google.android.gsf/com.google.android.gsf.update.SystemUpdateActivity</item>
        <item>com.google.android.gsf/com.google.android.gsf.update.SystemUpdateService$Receiver</item>
        <item>com.google.android.gsf/com.google.android.gsf.update.SystemUpdateService$SecretCodeReceiver</item>
        <item>com.google.android.gms/com.google.android.gms.update.SystemUpdateActivity</item>
        <item>com.google.android.gms/com.google.android.gms.update.SystemUpdateService$Receiver</item>
        <item>com.google.android.gms/com.google.android.gms.update.SystemUpdateService$ActiveReceiver</item>
        <item>com.google.android.gms/com.google.android.gms.update.SystemUpdateService$SecretCodeReceiver</item>
    </string-array>

In fact it disable receivers that cause wakelock directly in the framework. These receivers have to do with stock android OTA updates, no use for us.

Thanks if you can implement this.

Github modify what I put in there, it remove </sting-array> ..... you should go to xda thread or if you want I can try to send you text file.

Source : 

http://forum.xda-developers.com/oneplus-one/themes-apps/mod-google-play-services-update-wake-t3078082

**Comment by X-s** [comment]
can you edit it and push give me? thanks

**Comment by dadaz** [comment]
Ok, I can do that, but don't know how to edit a file on github. I'll copy file and attach modified file to comment. Just remove .txt at the end.


[arrays.xml.txt](https://github.com/X-s/patchrom_miui_oneplus_bacon/files/42457/arrays.xml.txt)

**Comment by X-s** [comment]
can you make sure that change can work?

**Comment by dadaz** [comment]
no, I don't have the need for compiling. If you can compile only framework and send me, I can try it.

**Comment by X-s** [comment]
give me a email and i will give you framework apk

**Comment by dadaz** [comment]
dave.gares@gmail.com

Thanks.

**Comment by X-s** [comment]
send email ok

**Comment by dadaz** [comment]
It doesn't boot and phone is hot.

**Comment by X-s** [comment]
omg....

**Comment by X-s** [comment]
look can't work...not a good way to fix this problem...i will revert this chance

**Comment by dadaz** [comment]
Ok, I've found another solution for this problem with tasker app.

**Comment by dadaz** [comment]
Thanks anyway

**Comment by X-s** [comment]
thanks too.
