### ISSUE TITLE
MIUI7 Lollipop based

### ISSUE THREAD

**Issue by djsiropchik** [X-s/patchrom_miui_oneplus_bacon#20]
Hello, dev!

Thanks for your work for OnePlusOne. It's great rom.

http://en.miui.com/thread-151469-1-1.html - MIUI 7 Pathrom is released and support Lollipop.

I know that now miui 7 based on 4.4. Can we expect 5.0 (cos12) or 5.1 (cos12.1) based version in a few months?
Members would be happy. I will try to raise funds to support the development.

**Comment by drenninghoff** [comment]
Xiaomi's patchrom tool is based on 4.4.4 and doesn't support a Lollipop ROM as a base. Therefore there is nothing X-s can do to support Lollipop.

As long as Xiaomi doesn't release a patchrom tool for Lollipop, this won't change. Xiaomi are the ones who need to support Lollipop, not X-s.

So it doesn't make sense asking here, you need to ask Xiaomi to support Lollipop.

**Comment by X-s** [comment]
yes....must xiaomi suppot...
