### ISSUE TITLE
Change language 

### ISSUE THREAD

**Issue by Malzet** [X-s/patchrom_miui_oneplus_bacon#21]
Hey, thank you for this great port.
I have donwloaded and installed and I love it. But i have the problem, that default apps like Appstore and Themestore change language while loading. I use German and it works well and if I try to start these sytsemapps they show up in German but than change instant to Chinese.
Is there any way to fix this, or is it because of the Chinese Rom a problem that can't be fixed?
Hope you or anyone else can help me :)

**Comment by X-s** [comment]
sorry, the miui rom is not suppot German, like Appstore and Themestore only suppot chinese and english.

**Comment by Malzet** [comment]
Ah oke thank than I should use english :D
