### ISSUE TITLE
Mi Apps In English 

### ISSUE THREAD

**Issue by gohilhardeepsinh** [X-s/patchrom_miui_oneplus_bacon#22]
X-s How to use mi inbuilt apps in English , I cant understand Chinese Language .
![screenshot_com miui player_2015-09-18-20-15-48](https://cloud.githubusercontent.com/assets/10323048/9962213/39a8736e-5e42-11e5-924a-f583cbcf66dc.png)
![screen1](https://cloud.githubusercontent.com/assets/10323048/9962212/39a68a40-5e42-11e5-8476-b4f3a39c1d3f.png)

**Comment by X-s** [comment]
hummmmmm........because this app's data is all of chinese and not your country,  for example, music, which is China's song, so....i can't help you..you can use your music app. sorry

**Comment by gohilhardeepsinh** [comment]
Thank You For Your Answer  Sir , Another thing is sir i want to learn porting miui to our one plus If you can help me anyhow...?

**Comment by X-s** [comment]
yep, come on. :)

**Comment by gohilhardeepsinh** [comment]
Sir accept my request on hangout,  so i can contact you...

**Comment by gohilhardeepsinh** [comment]
From where i can start porting rom ? ,  is there Any complete tutorials for porting ?

**Comment by X-s** [comment]
http://github.com/micode
https://github.com/MiCode/patchrom/blob/miui-7/Patchrom%20Developer%20Guide.pdf

**Comment by gohilhardeepsinh** [comment]
Is officiall miui7 is based on Android 4.4.4

**Comment by X-s** [comment]
yep

**Comment by gohilhardeepsinh** [comment]
Is It Possible to port from android 5.1 ...?

**Comment by X-s** [comment]
no

**Comment by gohilhardeepsinh** [comment]
Okay thanks for your time...

**Comment by gohilhardeepsinh** [comment]
Dear Friend,  can i port miui from any Indian rom like in our mi4i model we have different apps,  all apps is in English or is there any way to use these apps directly.

**Comment by X-s** [comment]
maybe you can port mi4i apps to oneplus miui v7

**Comment by gohilhardeepsinh** [comment]
Is there any guidance for that...? Can you suggest me how to do this...?
