### ISSUE TITLE
OTAs don't work

### ISSUE THREAD

**Issue by karan-github** [X-s/patchrom_miui_oneplus_bacon#24]
Firstly, thank you X_s for the best MIUI port for OnePlus One.

Whenever, I try to update by downloading OTA update, I get this error:
"error executing updater binary"

I'm using TWRP 2.8.6.0.

Please suggest. Thanks!

**Comment by gohilhardeepsinh** [comment]
Dear Karan You need To Flash Full Updated ROM . That's the only solution i found right now .

**Comment by karan-github** [comment]
I understand but flashing every week is a tedious task.

**Comment by gohilhardeepsinh** [comment]
Yupp i know , i am also tired of this things .

**Comment by X-s** [comment]
hi, can you give me a twrp recovery logcat? (advanced, logcat, then to sdcard/twrp/ find it and give me), thanks

**Comment by karan-github** [comment]
I emailed you the log, see if that's useful.

I have flashed 2 ROMs after that:
1. ColorOS
2. MIUI by WXL (Current ROM)

**Comment by X-s** [comment]
you should flash X_s MIUI ROM with twrp then give me logcat,pls

**Comment by karan-github** [comment]
Ok. Flashing & sending it in sometime. Thanks!

**Comment by X-s** [comment]
1.wipe data
2.flash x_s miui rom (old version)
3.download the ota zip
4.flash new version ota file
5.twrp, advanced, logcat and give me emali
thanks

**Comment by X-s** [comment]
if you don't change the system files, the ota will successful, good luck

**Comment by gohilhardeepsinh** [comment]
Thanks X-s we will try that .

**Comment by karan-github** [comment]
X-s I think the problem exists because of GApps.

1. OTA was successful without flashing GApps.
2. OTA was unsuccessful if GApps are flashed. I use nano version of Open GApps (http://opengapps.org/).

I have also sent you the error log for the second scenario. Probably, there is some system file which is being corrupted by flashing GApps.

**Comment by X-s** [comment]
i found somethings with the logcat.
Verifying current system...
failed to stat "/system/priv-app/QuickSearchBox.apk": No such file or directory
maybe the Gapps has changed this app? you should to check it.
good luck
