### ISSUE TITLE
stagefright vulnerability

### ISSUE THREAD

**Issue by skriv86** [X-s/patchrom_miui_oneplus_bacon#26]
Is it possible to fix stagefright vulnerability? In the settings info security patch level is 2015-11-01, but it is still stagefright vulnerable.
May be this could help, this is the CM11 Racpu_ ROM from xda, it is patched for stagefright v2
forum.xda-developers.com/oneplus-one/development/rom-racpufinal-stagefright-patch-t3212440

**Comment by X-s** [comment]
the settings info add by Xiaomi MIUI, and i don't know why they add. i will ask them.

**Comment by skriv86** [comment]
So no chance to build cm11 base with fixed libstagefright*.so files?(

**Comment by X-s** [comment]
no.

**Comment by X-s** [comment]
maybe Xiaomi chance but not give us source to build this files.

**Comment by X-s** [comment]
i remove this info on settings.
https://github.com/X-s/patchrom_miui_oneplus_bacon/commit/dd55e88a696982ec4a5baa4ea312acaf7cccd5da
