### ISSUE TITLE
Issue running the automake.sh

### ISSUE THREAD

**Issue by rajesheber** [X-s/patchrom_miui_oneplus_bacon#3]
I cloned your entire project and then tried to run ./automake.sh. I had provided the build no and my stockrom.zip as second paramter. Is this correct

**Comment by X-s** [comment]
"Usage: ./auto_make.sh   BUILD_NUMBER   LAST_TARGET"
EG:
BUILD_NUMBER=5.5.13
LAST_TARGET=last_target_files_5.5.8.zip(last make fullota with target files zip)

**Comment by X-s** [comment]
if you don't want to make ota package,you can use "make fullota BUILD_NUMBER=5.5.13"

**Comment by rajesheber** [comment]
thanx you so much for the response :) appreciate it. I had replaced your stock rom folder with contents from cm11s XNPH05Q deodexed and rooted. Had replaced the boot.img in the others folder and the meta data folder. Any other changes i need to make to have his succesfull.

**Comment by rajesheber** [comment]
when i ran the command "make fullota BUILD_NUMBER=5.5.13" .It gives me the following error
Sign target files
ERROR: no key specified for:

  ota-miui-oppo-MicrospurCamera.apk
  ota-miui-oppo-SuperZoomOnePluseCapMode.apk
  ota-miui-oppo-RawCamera.apk
  ota-miui-oppo-DoubleExposureCamera.apk
  ota-miui-oppo-FilterCamera.apk
  ota-miui-oppo-HDRCamera.apk
  ota-miui-oppo-GifCamera.apk
  ota-miui-oppo-NightCamera.apk
  ota-miui-oppo-SuperZoomCamera.apk
  ota-miui-oppo-SlowShutterCamera.apk
  ota-miui-oppo-PasserbyMode.apk
  ota-miui-oppo-FaceBeautyCamera.apk
  ota-miui-XiaomiBaiduInput.apk
  ota-miui-oppo-VoiceBeautyCamera.apk
  OppoCameraModH.apk
  Settings_ex.apk
  StockSettings.apk

Use '-e <apkname>=' to specify a key (which may be an
empty string to not sign this apk).
Build full ota package: /home/rajesheber/Desktop/patchrom/patchrom_miui_oneplus_bacon/out/fullota.zip
unzipping target target-files...
warning [/home/rajesheber/Desktop/patchrom/patchrom_miui_oneplus_bacon/out/target_files.zip]:  zipfile is empty

   ERROR: failed to unzip input target-files "/home/rajesheber/Desktop/patchrom/patchrom_miui_oneplus_bacon/out/target_files.zip"

make: *** [fullota] Error 1

**Comment by X-s** [comment]
https://github.com/X-s/patchrom_miui_oneplus_bacon/commit/31a784799263c05115eb79556fd839eaa8b91ffa

**Comment by X-s** [comment]
add apks sign to metadata/apkcerts.txt

**Comment by rajesheber** [comment]
thanx it solved the signing issue but have one more last error. Could you please help
Running : make ullota BUILD_NUMBER=5.5.13 getting this error
=============================================================================
done.
Build full ota package: /home/rajesheber/Desktop/patchrom/patchrom_miui_oneplus_bacon/out/fullota.zip
unzipping target target-files...
using device-specific extensions in .
using prebuilt boot.img...
Traceback (most recent call last):
  File "/home/rajesheber/Desktop/patchrom/tools/releasetools/ota_from_target_files", line 884, in <module>
    main(sys.argv[1:])
  File "/home/rajesheber/Desktop/patchrom/tools/releasetools/ota_from_target_files", line 852, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/rajesheber/Desktop/patchrom/tools/releasetools/ota_from_target_files", line 432, in WriteFullOTAPackage
    Item.GetMetadata(input_zip)
  File "/home/rajesheber/Desktop/patchrom/tools/releasetools/ota_from_target_files", line 163, in GetMetadata
    name, uid, gid, mode = columns[:4]
ValueError: need more than 2 values to unpack
make: *** [fullota] Error 1
=========================================================================

**Comment by X-s** [comment]
please check your device dir (metadata/filesystem_config.txt) ,the txt need more than 4 values

**Comment by rajesheber** [comment]
Thank you very much. it resolved the issue and was able to create the fullota. Will report after flashing

**Comment by X-s** [comment]
Good luck
