### ISSUE TITLE
Lock screen notifications and google play store bug

### ISSUE THREAD

**Issue by rajesheber** [X-s/patchrom_miui_oneplus_bacon#4]
I am not able to get notifications on lockscreen after enabling them in the notificaton setting and permissions for pop-up window. Any resolution here will be helpful.
  Another issue is not able to install any apps using the google play store. It throws an error" Not enough space on internal drive" even thought i have aroubd 40 GB free space.

**Comment by X-s** [comment]
On the first lock screen notification, I did not encounter this problem on my oneplus, my base package is CM11 M11.
As for Google play showed that the problem of insufficient storage space, this is the patchrom BUG, we also waiting for repair

**Comment by rajesheber** [comment]
oh ok. I am using your package with CM11 M11 and still dont get notification on lockscreen. Any resolution that you might suggest. Do you have plans to upgrade your base package to CM 11s  XNPH05Q which contains Max audio.

**Comment by X-s** [comment]
the package of cm11s xhph05q have a problem. None can use the so with libselinux and libsechook..will can not install apk

**Comment by rajesheber** [comment]
oh i see. Is the problem also with XNPH44S build ?

**Comment by X-s** [comment]
i have no idea..you can do try it..good luck

**Comment by rajesheber** [comment]
I am currently trying both the builds. Will update you when i have some update. Thank yo so much for the  responses and assistance with my errors. Really appreciate it.

**Comment by X-s** [comment]
Glad to see people around the world like MIUI. Thank you

**Comment by rajesheber** [comment]
Yes one of the best Android UI with good functionality. Trying to get a build since most of my friends want MIUI with max audio and lockscreen notifications :)

**Comment by rajesheber** [comment]
Tested one build with miui v6 and color os for oneplus one. It doesnt contain the google play store bug. So would this issue still be linked to MIUI bug u think ?

**Comment by X-s** [comment]
i'm not sure...Many MIUI ROM authors have this problem. sorry

**Comment by rajesheber** [comment]
No problem thanx for the response

**Comment by X-s** [comment]
nothing

**Comment by dado82rm** [comment]
sorry for asking, and don't be offended.
do you think that this can help to see if there are some errors or changes related to the storage error?? 
https://source.android.com/devices/storage/config-example.html

**Comment by X-s** [comment]
on the 5.5.15 version rom.google play is fix. :)

**Comment by dado82rm** [comment]
i have installed the zip below yesterday in multirom  but i still have the problem. http://miuirom.xiaomi.com/rom/u27615941/5.5.15/miui_bacon_xs_5.5.15_e5108a729a_4.4.zip
it works very well but storage same as usual...
i will try to clean install without multirom...

**Comment by X-s** [comment]
don't use multirom..try it again

**Comment by dado82rm** [comment]
i tryed just now i cleared everything format data wipe everything but don't work
but i realized that i changed the format to f2fs now i changed to ext4 and is installing...

**Comment by dado82rm** [comment]
nothing... doesn't work.... do you think i should fastboot the stock cm11s? and then reflash the miui? i was on cm12s last update made by ota from cm11s 05Q

**Comment by dado82rm** [comment]
sorry again for disturbing but i have tryed to go stock cm11s via fastboot and then reflash miui via twrp
i don't understand why it still doesn'w work can you tell me how do i need to do?
maybe i need to fastboot to an earlier version like 44S?

**Comment by rajesheber** [comment]
Yes i tested the latest build now and confirm that the google play store error still exists. X-s any changes you need us to test let us know.

**Comment by X-s** [comment]
Sorry,Sorry..that is my wrong,in fact Google market or no repair.. I'm very sorry.. :(

**Comment by rajesheber** [comment]
Thanx X-s for that confirmation. Trying to understand how the latest MIUI v6 based on color os doesn't have the google play store bug. It works well. any clues

**Comment by X-s** [comment]
i am try porting miui6 to color based...will coming soon

**Comment by rajesheber** [comment]
Thats wonderful. As i was asking before any guidelines as how to port stock o5q(kitkat build) rom of cm11s which carries the maxaudio ?

**Comment by dado82rm** [comment]
Same here i am not a developer but i love soing/tring this things i also truyed to use patchrom but when i arrived to fix errors like smali... i dont know what to do i dont understand that "smali language"

**Comment by dado82rm** [comment]
can we just ask to Relic242 how did i fixi it?

**Comment by rajesheber** [comment]
ask Relic242 for fixing play store bug u meant

**Comment by ToRvaLDz** [comment]
I'm still having no notifications on lock screen on 5.8.14, no play store issues.
