### ISSUE TITLE
New ROM build issue

### ISSUE THREAD

**Issue by rajesheber** [X-s/patchrom_miui_oneplus_bacon#5]
I had flashed the new fullota.zip which was built using your guidance. I built two build with changes to recovery.fstab. One build hung at oneplus one logo and another said updater script error. How can i check the logs for the issue. Kindly help. Attaching my recovery.fstab and updater script(kindly rename the file ext)

![recovery fstab](https://cloud.githubusercontent.com/assets/12206311/7628785/eb8168d2-fa44-11e4-95e2-248da111a4c1.jpg)
![updater-script](https://cloud.githubusercontent.com/assets/12206311/7628786/eb899e62-fa44-11e4-8539-0e4aef00ad16.jpg)

**Comment by X-s** [comment]
sorry,i can't see these pictures...it toast me errors
https://cloud.githubusercontent.com/assets/12206311/7628785/eb8168d2-fa44-11e4-95e2-248da111a4c1.jpg has error

**Comment by rajesheber** [comment]
i had changed those extensions so that i can upload. If you can download and change ext should work or else let me know any other location where i can send these files would help. thanx

**Comment by X-s** [comment]
i can't see anywhere.that links can not see

**Comment by rajesheber** [comment]
oh ok. anyway i can upload /email these files to you ? Do let me know. thanx

**Comment by X-s** [comment]
xsmumu@gmail.com. give me a message
