### ISSUE TITLE
Notification lock screen

### ISSUE THREAD

**Issue by rajesheber** [X-s/patchrom_miui_oneplus_bacon#9]
I find that mail notifications are appearing on the lock screen but some apps like news apps don't show notifications on the lock screen. Mail app am using is mailwise which shows notification on the lock screen but others don't. anyway we can make the notification manager push that to the lock screen

**Comment by ismethr** [comment]
You can change that on the setup options

**Comment by rajesheber** [comment]
Did you mean the settings panel ===> notifications ?

**Comment by ismethr** [comment]
Yes Notifications===> manage notifications ===> Select the App===> Show floating notifications

**Comment by rajesheber** [comment]
yes have done that but doesn't show up except the mail app that i use. And anyway that it can light up the lock screen when the notifications comes when the screen is off ?

**Comment by X-s** [comment]
you can into  Settings >>Notifications >> Manager notifications >> select your app >> Allow notifications

**Comment by rajesheber** [comment]
have done that but not all notifications show up on lockscreen except the mail notifications.

**Comment by X-s** [comment]
your mean is the email can't turn off on lockscreen?

**Comment by rajesheber** [comment]
I meant that only email appears on the lock screen and the screen turns on. Rest of the notifications don't appear on the lock screen.

**Comment by ToRvaLDz** [comment]
Same here
